language: cpp
compiler: gcc
os: linux
dist: bionic
cache: ccache

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
            - cmake
            - ninja-build
            - ccache
            - libx11-dev
            - libxcursor-dev
            - libgif-dev
            - libgtest-dev
            - libfreetype6-dev
            - libjpeg-dev
            - libz-dev
            - libpng-dev
            - libtinyxml-dev
            - libpixman-1-dev
            - zlib1g-dev

env:
  - SHARED=OFF

before_install:
  - if [ "$SHARED" == "ON" ]; then sudo apt-get install -y liballegro4.2-dev ; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ] && [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

before_script:
  - cd /usr/src/gtest; sudo mkdir build; cd build; sudo cmake ..; sudo make; sudo make install
  - cd $TRAVIS_BUILD_DIR
  - ccache -z
  - mkdir build
  - cd build
  - cmake -G Ninja .. -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/build/install -DWITH_DESKTOP_INTEGRATION=ON -DUSE_SHARED_ALLEGRO4=$SHARED -DENABLE_TESTS=ON

script:
  - ninja libresprite
  - ninja install
  - cd "${TRAVIS_BUILD_DIR}"
  - ccache -s

after_success:
  - |
    if [ "$TRAVIS_BRANCH" == "master" ]; then
      cd build
      wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
      chmod +x linuxdeploy-x86_64.AppImage
      ./linuxdeploy-x86_64.AppImage --appdir AppDir
      cp -r install/share/icons/* AppDir/usr/share/icons
      mv install/share/libresprite/data/ AppDir/usr/bin/
      ./linuxdeploy-x86_64.AppImage --appdir AppDir  -e install/bin/libresprite -d ../desktop/libresprite.desktop --output appimage
      mkdir out
      mv LibreSprite-*.AppImage -t out
      ls -lh out/*
      wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
      bash upload.sh out/*
    fi

branches:
    except:
      - # Do not build tags that we create when we upload to GitHub Releases
      - /^(?i:continuous.*)$/

notifications:
  email: false
