name: Windows x86

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32
        release: false
        update: false
        install: >-
          base-devel
          git
          mingw-w64-i686-nodejs
          mingw-w64-i686-gcc
          mingw-w64-i686-cmake
          mingw-w64-i686-make
          mingw-w64-i686-curl
          mingw-w64-i686-freetype
          mingw-w64-i686-giflib
          mingw-w64-i686-libjpeg-turbo
          mingw-w64-i686-lua
          mingw-w64-i686-libpng
          mingw-w64-i686-libwebp
          mingw-w64-i686-pixman
          mingw-w64-i686-SDL2
          mingw-w64-i686-SDL2_image
          mingw-w64-i686-tinyxml2
          mingw-w64-i686-v8
          mingw-w64-i686-zlib
          mingw-w64-i686-libarchive

    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - shell: msys2 {0}
      run: |
        mkdir build
        cd build
        cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
        make -j 4
        cd ..
        node package_win.js build/bin/libresprite.exe
        cp /mingw32/bin/snapshot_blob.bin ./build/bin
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: libresprite-development-windows-i686
        path: |
          build/bin/*
